development:
  step1:
    order: 0
    partner_name: pending
  step2:
    order: 100
    partner_name: pending
  live:
    order: 200

test:
  step1:
    order: 0
    partner_name: pending
  step2:
    order: 100
    partner_name: pending
  live:
    order: 200
