development:
  "https://rp1.serviceprovider.com/auth/saml/metadata":
    partner_account: DHS-CBP
    name: "Test Agency App"
    dashboard_identifier: 123
    integration_status: live

  "urn:gov:gsa:SAML:2.0.profiles:sp:sso:localhost":
    partner_account: GSA-FAS-TTS
    name: "Test SP"
    dashboard_identifier: 456
    integration_status: live

test:
  "https://rp1.serviceprovider.com/auth/saml/metadata":
    partner_account: DHS-CBP
    name: "Test Agency App"
    dashboard_identifier: 123
    integration_status: live

  "https://aal3.serviceprovider.com/auth/saml/metadata":
    partner_account: GSA-FAS-TTS
    name: "Test SP"
    dashboard_identifier: 456
    integration_status: live
