development:
  DHS-CBP:
    name: "U.S. Customs and Border Protection"
    agency: DHS
    partner_account_status: active
    crm_id: 123456
    became_partner: "2018-09-20"
    contacts:
      - "first.person@cbp.dhs.gov"
      - "second.person@cbp.dhs.gov"

  GSA-FAS-TTS:
    name: "Technology Transformation Services"
    agency: GSA
    partner_account_status: active
    crm_id: 234567
    became_partner: "2019-04-16"
    contacts:
      - "first.person@gsa.gov"
      - "second.person@gsa.gov"

test:
  DHS-CBP:
    name: "U.S. Customs and Border Protection"
    agency: DHS
    partner_account_status: active
    crm_id: 123456
    became_partner: "2018-09-20"
    contacts:
      - "first.person@cbp.dhs.gov"
      - "second.person@cbp.dhs.gov"

  GSA-FAS-TTS:
    name: "Technology Transformation Services"
    agency: GSA
    partner_account_status: active
    crm_id: 234567
    became_partner: "2019-04-16"
    contacts:
      - "first.person@gsa.gov"
      - "second.person@gsa.gov"
